### ISSUE TITLE
raw download issue

### ISSUE THREAD

**Issue by kquirolo** [jackiekazil/data-wrangling#1]
GitHub displayed error: "(Sorry about that, but we can’t show files that are this big right now.)" but allowed option to [View Raw](https://github.com/jackiekazil/data-wrangling/blob/master/data/chp3/data-text.xml?raw=true).

Raw view doesn't include tabs, making code provided in book throw an error.

Here is alternate (Python 3) code [from pydocs](https://docs.python.org/3/library/xml.etree.elementtree.html) that worked for me:

```
from xml.etree import ElementTree as ET

# this opens data-text.xml and read it as a string into variable read_xml
read_xml = open('data-text.xml').read()

# this finds the root from xml stored as a string
root = ET.fromstring(read_xml)
print(root) # for Python 2.7 use > print root
```

**Comment by kjam** [comment]
Hi @kquirolo,

Sorry I'm just now seeing this issue. Did you install the repository locally? If so, you should be able to use the file as is. Otherwise, can you tell me what line threw an error? Thanks in advance!

-katharine
