### ISSUE TITLE
"How to import XML Data" on page 57 with Python 3.6.3.

### ISSUE THREAD

**Issue by jcvdlugt** [jackiekazil/data-wrangling#11]
I try to run "How to import XML Data" on page 57 with Python 3.6.3.  However I get the following errors:
TypeError: unhashable type: 'dict_keys'.;
TypeError: 'dict_keys' object does not support indexing.
Unsuccessfully I have tried to write the code with a 'list' in Python 3.6.3.
Can you please give me the code for Python 3.6.3.?
Most appreciated ... Johannes

**Comment by kjam** [comment]
Hi Johannes,

For Python 3, you need to transform the dictionary keys to a list. So this should work:

```
lookup_key = list(item.attrib.keys())[0]
```

Let me know if that fixes your problem!

-kj

**Comment by jcvdlugt** [comment]
Hi Katharine,

 

Yes, this fixes the problem.

Thank you very much for your help!

 

The book that you have written about “Data Wrangling  ...” is very helpful and easy to understand.

 

Best regards ... Johannes

**Comment by kjam** [comment]
Great to hear! Happy Wrangling! :hugs:
