### ISSUE TITLE
Is a Python 3 version of this book in the works or available?

### ISSUE THREAD

**Issue by lazarillo** [jackiekazil/data-wrangling#19]
This isn't an *issue* per se.  I *love* the style of your writing; it is clear that the you wanted to focus upon *educating* the reader, instead of making sure you delved into all the gory details of each method.

However, Python 2.7 is now getting very old, especially considering your book was fairly recently published. I was curious if a Python 3 version is either in the works or if you already have one available somewhere (perhaps provided to folks who can prove they bought the book).

Thank you!
Regards,
Mike

**Comment by jackiekazil** [comment]
Thanks for the message! Unless @kjam is working on something that I don't know about, there is no Python 3 version of this book in the works.

**Comment by ajholman** [comment]
@jackiekazil I am trying to work through chapter 5 and having lots of problems with slate, pdfminer, etc.  Specifically, I get no print results from this (p. 97)--any recommendations? I've exhausted google searches and stackoverflow for possible solutions.

`pdf_txt = 'en-final-table9.txt
openfile = open(pdf_txt, 'r')

for line in openfile:
     print (line)`

**Comment by jackiekazil** [comment]
@ajholman can you post this to a new issue: https://github.com/jackiekazil/data-wrangling/issues/new

**Comment by jackiekazil** [comment]
@lazarillo GOOD NEWS! Python 3 version is coming!!!
