### ISSUE TITLE
Chapter 4. Working with Excel Files

### ISSUE THREAD

**Issue by TheCrusader** [jackiekazil/data-wrangling#8]
Hi Jackie:

I think this code has a little bug on line that says 'if count < 10:' because I got empty list as the result.
count = 0
data = {}
for i in xrange(sheet.nrows):
    if count < 10:
        if i >= 14:
            row = sheet.row_values(i)
            country = row[1]
            data[country] = {}
        count += 1

print data

After doing some investigation, I found that it should be written as 'if count < 20' as follows:
count = 0
data = {}
for i in xrange(sheet.nrows):
    if count < 20:
        if i >= 14:
            row = sheet.row_values(i)
            country = row[1]
            data[country] = {}
        count += 1

print data

**Comment by kjam** [comment]
Hi there,

Thanks for the report. If you read the paragraph after that code, you see it says "If you run your script with the counter in it where count < 10, you will see from the output that we have not yet reached the row where the country names start." 

So the book continues until you try count < 20. 

Hope that helps!
-kj

**Comment by TheCrusader** [comment]
Hi Jackie:
Oops, you're right. Sorry, I was to excited to try that code.
Thanks,
Budhi



On Monday, July 24, 2017, 2:54:59 AM EDT, Katharine <notifications@github.com> wrote:


Hi there,

Thanks for the report. If you read the paragraph after that code, you see it says "If you run your script with the counter in it where count < 10, you will see from the output that we have not yet reached the row where the country names start."

So the book continues until you try count < 20.

Hope that helps!
-kj

**Comment by kjam** [comment]
no worries! Hope you enjoy the rest of the book!
